DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.urls import include
admin.autodiscover()
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('links/', views.links, name='links'),
    path('pool/', views.pool, name='pool'),
    path('blog/', views.blog, name='blog'),
    path('videopost/', views.videopost, name='videopost'),
    path('(?P<parametr>\d+)/', views.blogpost, name='blogpost'),
    path('registration/', views.registration, name='registration'),
    path('newpost/', views.newpost, name='newpost'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Авторизация',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class PoolForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length = 2, max_length = 50)
    auto = forms.CharField(label='Напишите марку вашего авто', min_length = 1, max_length = 100)
    service = forms.ChoiceField(label='Оцените качество работы сервиса',
                                choices=(('1','Отлично'),
                                         ('2','Хорошо'),
                                         ('3','Среднее'),
                                         ('4','Ужасно')), initial=1)
    feedback = forms.CharField(label='Ваш отзыв',
                              widget=forms.Textarea(attrs={'rows':12,'cols':20}))
    email = forms.EmailField(label='Ваш e-mail', min_length = 5)
    repeat = forms.ChoiceField(label='Обратитесь к нам еще раз?',
                               choices=(('1','Да'),
                                         ('2','Нет')), initial=1)
    consent = forms.BooleanField(label='Я согласен на отправку моего отзыва', required=True)

class CommentForm (forms.ModelForm):

    class Meta:

        model = Comment # используемая модель

        fields = ('text',) # требуется заполнить только поле text

        labels = {'text': "Комментарий"} # метка к полю формы text

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title','description','content','image')
        labels = {'title': "Заголовок",'description': "Краткое содержание",'content': "Полное содержание",'image': "Изображение"}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Мы БК-сервис.</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2> <br />

{% for post in posts %}

<hr/>

<div class="">

    <h2> {{post.title}} </h2>

    <h4> {{post.posted}} </h4>

    <p> {{post.description}} </p>
    <p>Автор:{{ post.author }}</p>
    <p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>

</div>

{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}

<h2> {{post_1.title}} </h2>

        {% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
            <img src="{{post_1.image.url }}" alt="Изображение" widht="300" height="200" />
        {% endif %}

<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}
<p>Автор:{{ post_1.author }}</p>

{% if user.is_authenticated %}

    <h3>Добавить комментарий</h3>

    <form method="POST" >{% csrf_token %} {# защита от атак CSRF#}

        <div>

            {{form.as_p}}

            <button type="submit" class="save btn btn-default" > Отправить комментарий </button>

        </div>

    </form>

{% else %}

    <h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>

{% endif %}

{% for comment in comments %}

    <hr/>

    <h7> {{comment.date}} </h7>

    <h5> {{comment.author}} </h5>

    <p> {{comment.text|linebreaksbr}} </p>

{% endfor %}

<p><a href="{% url 'blog' %}" class="btn btn-primary btn-large">Назад</a></p><br />

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    БК-сервис<br />
    Железнодорожная 52<br />
    <abbr title="Телефон">Телефон:</abbr>
    89117987537
</address>

<address>
    <strong>Техническая поддержка:</strong>   <a href="mailto:Support@example.com">mr.kirik911@mail.ru</a><br />
    <strong>Отдел маркетинга:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

        <li data-target="#myCarousel" data-slide-to="1"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

    
    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img src="{% static 'app/content/1.jpg'%} " alt="Первый слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Наш первый проект

                    <a class="btn btn-default" href="/about">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/2.jpg'%}" alt="Второй слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Кузовной ремонт

                    <a class="btn btn-default" href="/about">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/3.jpg'%} " alt="Третий слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Технические доработки

                    <a class="btn btn-default" href="/about">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>

<div class="jumbotron">
    <h1>БК-Сервис</h1>
    <p class="lead">Добро пожаловать, вы находитесь на сайте БК-Сервис. Наш сервис специализируется на ремонте и технических доработках любой сложности автомобилей ВАЗ(Lada).
	Наш сервис проконсультирует вас по поводу технических доработок вашего автомобился и поможет с выбором тюнинг компонентов. 
	Основное направление наших доработок это — зимний дрифт на автомобилях классического семейства ВАЗ.</p>
    <p><a href="/about" class="btn btn-primary btn-large">О нас &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Тюнинг-ателье</h2>
        <p>
            Наш сервис поможет вам установить тюнинг-комплектующие на ваш автомобиль.
			Мы с радостью подготовим ваш автомобиль классического семейства ВАЗ к зимнему дрифту и не только.
        </p>
        <p><a class="btn btn-default" href="/about">О нас &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Автосервис</h2>
        <p>Мы работаем не только с различными проектами, но и с гражданскими автомобилями. Мы оказываем услуги любой сложности при ремонте автомобилей </p>
        <p><a class="btn btn-default" href="/about">О нас &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Шиномонтаж</h2>
        <p>Также в нашем автосервисе есть услуги шиномонтажа легковых автомобилей.</p>
        <p><a class="btn btn-default" href="/about">О нас &raquo;</a></p>
    </div>
	<div class="col-md-4">
        <h2>Покраска</h2>
        <p>
            Наш сервис поможет вам освежить внешний вид вашего автомобился. У нас есть услуги покраски и ремонта кузовных элементов.
        </p>
        <p><a class="btn btn-default" href="/about">О нас &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} — БК-Сервис </title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'app/content/logo.png' %}" width="30px" alt="logo" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Домашняя страница</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'links' %}">Ссылки</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    {% if user.is_superuser %}
                        <li><a href="{% url 'newpost' %}">Новая статья</a></li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    <li><a href="{% url 'pool' %}">Отзыв</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<div class="jumbotron">
    <h2>{{ title }}.</h2>
    <h3>{{ message }}</h3>

    <address>
    <strong>Наши социальные сети:</strong><br />
    <a href="https://vk.com/id136233271"><img src="{% static 'app/content/vk.jpg' %}" width="50px" alt="Вконтакте"/></a>
    <a href="https://www.instagram.com/kirill_kayst/"><img src="{% static 'app/content/inst.jpg' %}" width="50px" alt="Инстаграм"/></a>
    </address>
</div>

{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте имя пользователя и пароль для входа в систему.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильное имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}
<div class="jumbotron">
<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

        <h3>Добавить статью</h3>
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div>
                {{ blogform.as_p }}
                <button type="submit" class="save btn btn-default">Сохранить статью</button>
            </div>
        </form>
</div>

{% endblock %}

app/templates/app/pool.html
{% extends "app/layout.html" %}

{% block content %}
{% if form != None %}

<h2>{{ title }}.</h2>

<br /><h3>Оставь свой отзыв</h3>
<div class="jumbotron">
    <form method="post">
        {% csrf_token %}
        <label id="t1" for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }}<br />
        <label for="{{ form.auto.id_for_label }}">{{ form.auto.label }}:</label>
        {{ form.auto }}<br />
        <label for="{{ form.service.id_for_label }}">{{ form.service.label }}:</label>
        {{ form.service }}<br />
        <label for="{{ form.feedback.id_for_label }}">{{ form.feedback.label }}:</label>
        {{ form.feedback }}<br />
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }}<br />
        <label for="{{ form.repeat.id_for_label }}">{{ form.repeat.label }}:</label>
        {{ form.repeat }}<br />
        <label for="{{ form.consent.id_for_label }}">{{ form.consent.label }}:</label>
        {{ form.consent }}<br />
        <input id="b1" type="submit" value="Отправить" />
    </form>
    
</div>
    <script>
        function b1_colorin(){$('#b1').css('color', '#000000');}
        function b1_colorout(){$('#b1').css('color', 'black');}
        $('#b1').mouseover(b1_colorin);
        $('#b1').mouseout(b1_colorout);
    </script>
    <script>
        function textclick(){$('#id_name').css('background-color', '#ff8b75');}
        function textclickoff(){$('#id_name').css('background-color', 'white');}
        $('#id_name').focus(textclick);
        $('#id_name').blur(textclickoff);
    </script>
    <script>
        function textclick(){$('#id_email').css('background-color', '#ff8b75');}
        function textclickoff(){$('#id_email').css('background-color', 'white');}
        $('#id_email').focus(textclick);
        $('#id_email').blur(textclickoff);
    </script>
    <script>
        function textclick(){$('#id_auto').css('background-color', '#ff8b75');}
        function textclickoff(){$('#id_auto').css('background-color', 'white');}
        $('#id_auto').focus(textclick);
        $('#id_auto').blur(textclickoff);
    </script>
{% else %}
<br /><h2>Спасибо за ваш отзыв</h2>
<h3>Убедитесь в том, что все написано правильно:</h3>
<ul>
    <li><span>Ваше имя: </span>{{ data.name }}</li>
    <li><span>Ваш автомобиль: </span>{{ data.auto }}</li>
    <li><span>Качество работы:</span>{{ data.service }}</li>
    <li><span>Ваш отзыв о нас: </span>{{ data.feedback }}</li>
    <li><span>Вернетесь ли вы: </span>{{ data.repeat }}</li>
    <li><span>Ваш e-mail: </span>{{ data.email }}</li>
    <li><span>Я согласен на отправление моего отзыва: </span>{{ data.consent }}</li>
</ul>
{% endif %}
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>

<form method="POST" > {% csrf_token %}

<div>

{{ regform.as_p}}

<button type="submit" class="save btn btn-default" > Зарегистрировать </button>

</div>

</form>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}


<div class="jumbotron">
        <h1>Дрифт по мокрому по кругу</h1>
        <video src="/media/video-08-12-20-10-20.mp4"
               controls="controls"
               width="900" height="500"
               poster="/media/3.jpg"></video><br/>
        <h1>Зимний дрифт на парковке</h1>
        <video src="/media/video-08-12-20-10-21.mp4"
               controls="controls"
               width="900" height="500"
               poster="/media/3.jpg"></video>
</div>

{% endblock %}